version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: ${APP_CONTAINER_NAME}
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: ${APP_CONTAINER_NAME}
      SERVICE_TAGS: dev
    working_dir: /var/www/
    volumes:
      - ${LARAVEL_ROOT_PATH}:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    logging:
      driver: ${APP_LOG_DRIVER:-json-file}
      options:
        max-size: ${APP_LOG_MAX_SIZE:-2m}
        max-file: ${APP_LOG_MAX_FILE:-10}

  #Nginx Service
  webserver:
    image: nginx:1.17.7-alpine
    container_name: ${WEBSERVER_CONTAINER_NAME}
    restart: unless-stopped
    tty: true
    volumes:
      - ${LARAVEL_ROOT_PATH}:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./logs/nginx/:/var/log/nginx/
      - ${SSL_PATH}:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      SSL:
      SSLCERT: ${SSL_CERTIFICATE}
      SSLKEY: ${SSL_KEY}
    logging:
      driver: ${WEBSERVER_LOG_DRIVER:-json-file}
      options:
        max-size: ${WEBSERVER_LOG_MAX_SIZE:-2m}
        max-file: ${WEBSERVER_LOG_MAX_FILE:-10}

  #MySQL Service
  db:
    image: mysql:5.7.29
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: ${DB_CONTAINER_NAME}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    logging:
      driver: ${DB_LOG_DRIVER:-json-file}
      options:
        max-size: ${DB_LOG_MAX_SIZE:-2m}
        max-file: ${DB_LOG_MAX_FILE:-10}

#Docker Networks
networks:
  default:
     external:
       name: ${NETWORK}
